version: 2

defaults: &defaults
  working_directory: ~/talar
  docker:
    - image: circleci/elixir:1.8.0-node-browsers
      environment:
        MIX_ENV: test
    - image: circleci/postgres:10.1-alpine
      environment:
        PGUSER: postgres
        PGPASSWORD: postgres
        POSTGRES_DB: talar_test
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
              - v2-deps-cache-{{ checksum "mix.lock" }}
              - v2-deps-cache
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - save_cache:
          key: v2-deps-cache-{{ checksum "mix.lock" }}
          paths:
              - _build
              - deps
              - ~/.mix
      - persist_to_workspace:
          root: ~/
          paths:
            - talar
            - .mix
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Wait for postgres to start
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run tests
          command: mix test
  credo:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run credo
          command: mix credo
  check_formatted:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Verify formatted
          command: mix format --check-formatted
  dialyzer:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - restore-cache:
          keys:
            - v1-plt-cache-{{ checksum "mix.lock" }}
            - v1-plt-cache
      - run: mix dialyzer --plt
      - save_cache:
          key: v1-plt-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - ~/.mix
      - run:
          name: Run dialyzer
          command: mix dialyzer
workflows:
  version: 2
  continuous_integration:
    jobs:
      - build
      - test:
          requires:
            - build
      - credo:
          requires:
            - build
      - dialyzer:
          requires:
            - build
      - check_formatted:
          requires:
            - build
